### ISSUE TITLE
Multitap not working for multi cd psx games

### ISSUE THREAD

**Issue by notanotherdev** [OpenEmu/Mednafen-Core#11]
I see the game I'm trying to play here in the multitap supported games (https://github.com/OpenEmu/Mednafen-Core/commit/8a5229f70d7f6d7a631c8cfcd3aa1231a0a1b079)

The game is: @"SLUS-00697" : @4, // Circuit Breakers (USA)

And it works fine alone. But when I create a .m3u file that contains its expansion pack (aka Bonus CD), the game itself and the expansion pack only see 2 controllers.

Is there a way to make multitap work with games that have more than 1 cd?

**Comment by clobber** [comment]
This is fixed as of OpenEmu 2.0.4, but you will need to reimport your games/m3u following the new method for [multi-disc games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game).
