### ISSUE TITLE
PSX PAL scanline settings

### ISSUE THREAD

**Issue by vin047** [OpenEmu/Mednafen-Core#12]
Hi, 

Curious to know why the PSX PAL scanline settings (from `psx.slstartp` and `psx.slendp`) aren't actually set, considering [they're referenced with suggested values of 14 and 275](https://github.com/OpenEmu/Mednafen-Core/blob/8f6125076a9cea938ec1d73883856d42f59f1d52/mednafen/psx/psx.cpp#L2429).

Was this done for idealogical reasons?

Thanks

**Comment by clobber** [comment]
A few comments in code doesn't mean they are 'suggested' values. We leave mostly everything to their default values.

**Comment by vin047** [comment]
Fair enough. Do you happen to recall how/where those values come from? Trying to figure out a decent value to use.

**Comment by clobber** [comment]
Don't know, but I'd prefer not to crop the screen to simulate overscan since it is going to differ from game to game anyway.
