### ISSUE TITLE
EUR games PS1, can't change default localisation from any menu

### ISSUE THREAD

**Issue by Sillv** [OpenEmu/Mednafen-Core#16]
Hi,

Is it possible to change the emulator language manually on PS1 ?

For example, I have the european version of Metal Gear Solid 1. But when i launch the game, only english language is available.

Is it possible to change core files (like DesmuMe) to do it ?

Regards,
Sillv

**Comment by clobber** [comment]
That's not how PS1 games worked. They either have built-in options for changing the language or there are localized versions of games, as you can see: http://redump.org/discs/quicksearch/metal-gear-solid/sort/system/
