### ISSUE TITLE
Analog Stuck Left

### ISSUE THREAD

**Issue by foleyoleyo** [OpenEmu/Mednafen-Core#3]
Analog always moving left will not respond to right movement. Holding a direct right only negates the left moment keeping me at a standstill. Can still move with and up and right or down and right.

**Comment by DarwinAwardWinner** [comment]
I'm seeing a similar issue. It's a little more complicated than what is described. It seems to happen randomly, but can easily be triggered in a few seconds by moving the analog stick left and right repeatedly. At some point, the analog input will become stuck as if the stick is pushed all the way in one direction, and acts as described in the report. However, it's possible to get the input unstuck by pushing the analog stick all the way in the same direction as it is moving. In the example given by the report above, where the stick is stuck left, moving the stick all the way to the left will fix it. The problem will then happen again a few seconds later if you continue using the analog stick. Basically, when the problem happens, the analog input acts like it has been recalibrated with the center point all the way on one end of the range. This happens in all PSX games and makes the analog sticks completely unusable in every game. I haven't tested the analog sticks on any other emulator (but I could if you wanted me to).

I am originally noticed the issue on the current "OpenEmu Experimental v1.0.4" available for download (as of 1 November 2015) , and I also see it in copy that I compiled myself today from revision 0460901683a89d67848beecfa10dc2c3bdb2c4c8, which lists itself as "127-g0460901-Release" in the about dialog. I've seen the issue with at least two different control pads: one PS2 controller connected via a 3rd-party USB adapter, and one PS4 controller, connected either by USB or Bluetooth. I can't remember, but I may have seen it with a Wiimote connected using WJoy (I didn't use that very much).
