### ISSUE TITLE
Completely broken after recent OpenEmuKit changes.

### ISSUE THREAD

**Issue by dvessel** [OpenEmu/Mednafen-Core#33]
I had to rollback a recent OpenEmuKit change for the Mednafen core to launch. 

https://github.com/OpenEmu/OpenEmuKit/commit/382ebf7562452842318ac3215d3960191dcb299f

Just a FYI, thanks.

**Comment by clobber** [comment]
Then you should report this in the main repo with what exactly "broke" means.

**Comment by dvessel** [comment]
Thought it would belong here since Mednafen was the only core that was affected but I haven’t tested every core.

reported here: https://github.com/OpenEmu/OpenEmu/issues/4748
