### ISSUE TITLE
mednafen_psx_hw_libretro.so, mednafen_psx_libretro.s: OpenBIOs issue

### ISSUE THREAD

**Issue by davidhedlund** [OpenEmu/Mednafen-Core#35]
I can reproduce the issue for Windows 11, and GNU/Linux.

* Retroarch: Online Updater -> Content Downloader -> Sony PlayStation -> 240pTestSuitePS1-EMU.zip
* Retroarch: Online Updater -> Core Downloader -> Sony - PlayStation (Beetle PSX HW)
* Retroarch: Online Updater -> Core Downloader -> Sony - PlayStation (Beetle PSX)
* Download pcsx-redux-nightly-*-x64.zip from https://github.com/pcsx-redux/nightlies/releases, extract it, copy openbios.bin to ~/.config/retroarch/system/, and rename it to scph5501.bin

I can use 240pTestSuitePS1-EMU.cue with the OEM BIOS, but not with OpenBIOS (black screen, and no error message in the terminal:
* Beetle PSX HW: retroarch --libretro ~/.config/retroarch/cores/mednafen_psx_hw_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue
* Beetle PSX: retroarch --libretro ~/.config/retroarch/cores/mednafen_psx_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

**Comment by clobber** [comment]
Uhh... you're in the wrong place. This project is OpenEmu, a macOS application.
