### ISSUE TITLE
Sticky analog stick.

### ISSUE THREAD

**Issue by Jakeysp** [OpenEmu/Mednafen-Core#6]
Hiya,

I have noticed in PS1 racing games (Example: NFS IV: High Stakes or Gran Turismo 2) that when driving with an analog stick, there is a tendency for the car to periodically veer hard left or right sometimes. You can compensate for this by moving the stick, eg. if the car veers left, you can compensate for it by steering right, but if you release the stick it will veer back left. This problem is not easily reproducible, it seems to be random and goes away after a bit. You can sometimes correct it by quickly moving the stick in the direction of veering followed by the opposite direction, but not always.

I am using an Xbox 360 wireless controller with the Tattie Bogle driver on OS X Yosemite. I have tried various settings on the dead zone in the driver control panel but it does not seem to impact the problem even if you set a huge dead zone or none at all. If I switch to d pad the problem disappears. So I don't think it is to do with the driver, but I am not completely sure.

I found a fix which might be related from Feb 9 (https://github.com/OpenEmu/Mednafen-Core/commit/8f29dfbb16d5f78cc01d93cdac44de725ece4bdf) but I'm not terribly familiar with Github, so I'm not sure if this fix has already made it into the version of Mednafen I am using or not. The problem occurs both on the current version downloaded by the in-app installer (v0.9.34) and on v0.9.36.4 if I manually try that one.

**Comment by MisterTea** [comment]
I also have this problem.
