### ISSUE TITLE
not a problem really, i think i'm just stupid, but I need help...

### ISSUE THREAD

**Issue by javixtms** [OpenEmu/Mednafen-Core#9]
First of all, i have to apologize about my english, I'm from Spain. So if it is difficult to read it, please don't be scared!

I know that it's not a real issue, but i've been trying to find a place to expose my problem and i couldn't find it.

I installed OpenEmu v1.0.4 and everything was great. Recently I tried with the experimental version and I was in shock when i saw that i had to complete some things manually. I tried with Sony Playstation games and I put the three archives needed in BIOS folder (scph5500.BIN, scph5501.BIN and scph5502.BIN). http://postimg.org/image/hozdnqu03/

I ran the game and it worked! I felt like a hacker (I'm not used to do those things). But I realized that i couldn't save states so i look throughout internet and i saw that maybe I should change my mednafen core. Here's come the problem. 

I downloaded the latest version as I could see in a comment (http://postimg.org/image/d1tblz6n7/), and I downloaded just the big file (http://postimg.org/image/7t2w1udlv/). I replaced it in the CORE folder (http://postimg.org/image/9m5sq5ysj/) and I drag the CORE file to the program too(I can't remember why and even in what order).

Watever… I ran again the game but nothing happens… No new windows, no advices… nothing. As if I never ran the game. It looks like the core was well installed (http://postimg.org/image/ucjqdzyar/) (http://postimg.org/image/5xbicxzdv/), but it doesn't work anymore. I downloaded another game but the result was the same.

Then I realized that having just 2 games in Playstation One folder, in all games folder there were some clones and I don't know why (http://postimg.org/image/4byqp7e23/). When I tried to ran those clones an advice told me that there is no core to ran those games and check if I'm connected to internet (but damn! I'm always connected!).

I reset presets writing that in terminal app:  "defaults delete org.openemu.OpenEmu". But it didn't work.

Now I don't know what to do…

any idea?

**Comment by clobber** [comment]
Sorry, we can't help you with this. You're going to have to wait until next release (coming soon) where we include the new systems and everything works.

**Comment by javixtms** [comment]
Ok thanks, ill wait for it! It's AWESOME the work you are doing here guys. Keep rocking! :D
